# turtlebot3
obstacle_range: 3.0 # The default maximum distance from the robot at which an obstacle will be inserted into the cost map in meters.
raytrace_range: 3.5 # The default range in meters at which to raytrace out obstacles from the map using sensor data.
use_sim_time: false

footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]] #The footprint of the robot specified in the robot_base_frame coordinate frame as a list in the format.
# robot_radius: 0.46 # The radius of the robot in meters, this parameter should only be set for circular robots, all others should use the footprint parameter described above.
footprint_padding: 0.01 # How much to pad (increase the size of) the footprint, in meters.

inflation_radius: 1.0 # The radius in meters to which the map inflates obstacle cost values.
cost_scaling_factor: 3.0 # A scaling factor to apply to cost values during inflation.

map_type: costmap
observation_sources: scan
scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

# # evarobot
# obstacle_range: 2.5
# raytrace_range: 3.0
# footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]
# footprint_padding: 0.01

# inflation_radius: 0.1

# observation_sources: laser

# laser: {sensor_frame: laser, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}