# turtlebot3
local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 10.0 # The frequency in Hz for the map to be updated.
  publish_frequency: 10.0 # The frequency in Hz for the map to publish display information.
  transform_tolerance: 0.5 # Specifies the delay in transform (tf) data that is tolerable in seconds.

  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

# # evarobot
# local_costmap:
#   global_frame: map
#   robot_base_frame: base_link
#   update_frequency: 5.0
#   publish_frequency: 5.0
#   transform_tolerance: 0.3
#   static_map: false # evarobot default: true
#   rolling_window: true
#   width: 4.0
#   height: 4.0
#   resolution: 0.05
#   inflation_layer: 
#     inflation_radius: 0.2       # 0.0 Localdeki alanlar